export * from './is-binary-digit'
export * from './is-oct-digit'
export * from './is-digit'
export * from './is-hex-digit'
export * from './is-alpha'
export * from './is-alphanumeric'
export * from './is-space'
export * from './is-multispace'
